pipeline {
    agent any

    stages {

        stage('Clonar repositorio') {
            steps {
                echo 'Clonando repositorio desde GitHub...'
            }
        }

        stage('Build Docker') {
            steps {
                bat '''
                cd KafkaMed
                docker compose build
                '''
            }
        }

        stage('Levantar servicios') {
            steps {
                bat '''
                cd KafkaMed
                docker compose up -d
                '''
            }
        }

        stage('Verificar contenedores') {
            steps {
                bat '''
                docker ps
                '''
            }
        }

        stage('Probar API') {
            steps {
                bat '''
                curl http://localhost:5000/stats
                '''
            }
        }

    }

    post {
        success {
            echo 'Pipeline ejecutado correctamente'
        }

        failure {
            echo 'Pipeline fallo'
        }
    }
}
